# Generated by Django 5.2.14 on 2026-06-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_confirmationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
